INSERT INTO `services` (`id`, `name`) VALUES
(1, 'Likes'),
(2, 'Followers'),
(3, 'Views'),
(4, 'Tweets'),
(5, 'Retweets'),
(6, 'Comments'),
(7, 'Custom comments'),
(8, 'Page Likes'),
(9, 'Post Likes'),
(10, 'Friends'),
(11, 'SEO'),
(12, 'Mentions'),
(13, 'Mentions with Hashtags'),
(14, 'Mentions Custom List'),
(15, 'Mentions Hashtag'),
(16, 'Mentions User Followers'),
(17, 'Mentions Media Likers');